spring:
  application:
    name: doto

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

    throw-exception-if-no-handler-found: true

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100

  redis:
    host: localhost
    port: 6379

  resources:
    add-mappings: false